### ISSUE TITLE
Arreglar codificación en formularios

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#11]
Una vez Edu Guzmán comentó algo sobre la codificación de los Strings en clase, he ido a mirar mis proyectos de JavaEE y he encontrado que los parámetros los obtenía mediante una función que convertía el String devuelto de `request.getParameter("pato")` de [ISO-8859-1][2] a [UTF-8][1]. El primer paso que hay que hacer para que vaya bien todo es arreglar el obtener parámetros usando el código que he hecho (el único que he hecho en Java en lo que llevamos de web) en el commit 8298c6a.

Usad `cosas.StringEncodingUtils.getParameter(request, "pato")` para que se haga todo esto solo (en lugar del ejemplo de arriba). Eso van en los Servlet que cojan cosas de un formulario (registro, editar perfil, búsqueda) y en los futuros que se vayan a hacer.

_Solo queda esperar que nos diga algo Edu para lo de MySQL, a parte de esto que es importante arreglar cuanto antes._

  [1]: https://en.wikipedia.org/wiki/UTF-8
  [2]: https://en.wikipedia.org/wiki/ISO/IEC_8859-1

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Arreglar inconsistencia con la codificación de los Strings](https://trello.com/c/4pyBIPhM/39-arreglar-inconsistencia-con-la-codificacion-de-los-strings)

**Comment by aangelcc** [comment]
Arreglado, se usa un filter que hace lo siguiente:` request.setCharacterEncoding("UTF-8");`. El filter es algo asi como un middleware
