### ISSUE TITLE
[Abro debate] ¿BorrarServlet debe redireccionar a la misma página de antes o a una de error?

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#16]
Mirad el hilo de [este commit](https://github.com/melchor629/AplicacionTecnologiasWeb/commit/768f98bb4ec5a4a476740b1580f7e6af6f08e103#diff-875c677b996e8a0f374560f8297b7095R107).

¿Debe BorrarServlet redireccionar a una página de error (como está ahora) o que redireccione a la página de editar _loQueFuera_ cuando hay un error? Un error tipo, campo obligatorio que está vacío (que es lo común).

**Comment by aangelcc** [comment]
Que campo puede estar vacio en BorrarServlet? Solo recibe parametros por URL que genera la aplicacion presumiblemente correctos. Borrar servlet lleva a error.jsp si se produce algun error ocasionado porque el usuario trapichee las variables. 

Cuando Borrar hace bien su trabajo redigirige al perfil informando debidamente de lo que ha hecho

**Comment by melchor629** [comment]
@aangelcc A, dijiste otra cosa ayer, o te entendí mal. Entonces redirije al 500 o 404, como quieras. Es más facil

**Comment by aangelcc** [comment]
Solucionado. Ver el commit [https://github.com/melchor629/AplicacionTecnologiasWeb/commit/b4cf4c01dbc55eaf279084dfb2cdf4c85a4afb9b](url)

Ahora se lanza una runtime Exception basicamente. Se sigue dando suficiente info para que podamos seguir debugueando a gusto. Sobre todo cuando tengamos que pasarlo todo a JSF, eso si que va a ser gracioso :)
