### ISSUE TITLE
Error "," en el perfil de los usuarios

### ISSUE THREAD

**Issue by xEDG** [melchor629/AplicacionTecnologiasWeb#17]
Se trata de un error menor, pero cuando me he metido con la cuenta de melchor, cuando miras en el perfil el contador de días que llevas estudiando algo o trabajando en algo, si no lleva más de 1 año, aparece como
", 4 días" por ejemplo, con una coma delante de los días.
Es un error sencillo en el código pero lo pongo porque hay que arreglarlo

![imagen](https://cloud.githubusercontent.com/assets/17827406/25624646/5d9ea096-2f5a-11e7-9ee6-3df22a67d128.png)

**Comment by melchor629** [comment]
@xEDG Me pondré a arreglarlo en un momento. Tecnicamente eso no deberia ocurrir, porque estaba bien. Pero como @aangelcc tocó ese código, la ha liado

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error "," en el Perfil](https://trello.com/c/olKFgyKH/49-error-en-el-perfil)

**Comment by melchor629** [comment]
Salgo guapo en la foto jeje xD
