### ISSUE TITLE
Comprobar que las páginas privadas se redirija fuera si no has iniciado sesión

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#18]
Por ahora (comprobado por mi) pasa en las siguientes páginas:

- [x] /busqueda.jsp
- [x] /editarAficion.jsp
- [x] /editarEstudio.jsp
- [x] /EditarAficion
- [x] /EditarPerfil
- [x] /EditarTrabajo
- [x] /PeticionAmistad (incluye un fallo de seguridad muy intenso)
- [x] /AmistadHandlerServlet (incluye un fallo de seguridad muy intenso)

Estas páginas no muestran nada, pero no redirigen:

- [x] /Borrar
- [x] /BuscarServlet
- [x] /Main

Supongamos que lo de @RodriRR no está bien:

- [ ] Lo que haya hecho Rodri

**Comment by aangelcc** [comment]
Al menos en todas las que llevo hechas lo he controlado y todo está funciona de forma adecuada

**Comment by aangelcc** [comment]
Arreglado en todas

**Comment by melchor629** [comment]
No están todas. Mira la lista

**Comment by aangelcc** [comment]
Ahora si xd. Y MainServlet no se porque no lo tenias marcado cuando si que tiene codigo de "redireccion":
` if (uLogged == null) {
            RequestDispatcher rd;
            request.setAttribute("error", true);
            rd = this.getServletContext().getRequestDispatcher("/index.jsp");
            rd.forward(request, response);
        } else {`

**Comment by melchor629** [comment]
No lo tiene, no en todos

**Comment by aangelcc** [comment]
Lo sigo dejando abierto por si surge algo mas

**Comment by melchor629** [comment]
No debería haber más porque los estuve comprobando todos los que había esta mañana, mas los que has tocado tu ahora. Ahora solo queda `/Main`. Y esperar a lo de Rodri.

**Comment by aangelcc** [comment]
Guay :+1:

**Comment by melchor629** [comment]
Con esto `/Main` ya redirige siempre cc7ae33
