### ISSUE TITLE
Cerrar sesión provoca NullPointer Exception

### ISSUE THREAD

**Issue by aangelcc** [melchor629/AplicacionTecnologiasWeb#21]
Hay que investigarlo por qué es, estoy en ello pero no se porqué pasa...

**Comment by melchor629** [comment]
@aangelcc Solo te pasa a tí

**Comment by aangelcc** [comment]
Pues ni zorra de por qué la verdad... Reinstalaré el netbeans o yo que se

**Comment by melchor629** [comment]
@aangelcc Seguro que no has hecho el undeploy...

**Comment by aangelcc** [comment]
Lo he hecho e incluso desde el panel del glassfish

**Comment by melchor629** [comment]
@aangelcc recrea la bd.

**Comment by aangelcc** [comment]
Lo cierro por ahora ya que a nadie le pasa. A mi me pasa pero es ajeno "en teoria" a nuestra app
