### ISSUE TITLE
Eliminar amistad no funciona

### ISSUE THREAD

**Issue by aangelcc** [melchor629/AplicacionTecnologiasWeb#22]
Desconozco si añadir amistad, hacen referencia a /PeticionAmistad que por algún motivo ya no existe (?). Es necesario que el boton enlace al sitio adecuado

**Comment by melchor629** [comment]
@aangelcc Creo que directamente nunca ha existido. Se puede modificar AmistadHandlerServlet para que maneje también el eliminar la amistad.

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ARREGLAR ELIMINAR PETICIÓN DE AMISTAD](https://trello.com/c/vOneJLHX/72-arreglar-eliminar-peticion-de-amistad)

**Comment by melchor629** [comment]
En las lineas [128](https://github.com/melchor629/AplicacionTecnologiasWeb/blob/master/web/web/perfil.jsp#L128) y [134](https://github.com/melchor629/AplicacionTecnologiasWeb/blob/master/web/web/perfil.jsp#L134) de `perfil.jsp` están los enlaces para pedir amistad o borrar amistad. Hay que adaptarlos al formato de Edu:
 - **URL** `/AmistadHandlerServlet`
 - **Parámetros**
    - `tipo` el tipo  de acción a hacer (en String)
    - `iduser` el ID del otro usuario

Esto en formato enlace seria `<%=cpath%>/AmistadHandlerServlet?tipo=algo&iduser=0`.

**Comment by xEDG** [comment]
Observaciones nuevas:
- Aparentemente la petición se envía correctamente.
- Permite aceptar y rechazar peticiones.
PERO:
- Si envias una nueva petición, peta en notificaciones.
- No se actualizan los objetos java (Si melchor acepta a manolito y luego lo elimina, en el perfil de manolito no sale que es amigo de melchor pero en el de melchor sí)

Seguiremos informando

**Comment by xEDG** [comment]
Arreglado, cierro.

https://github.com/melchor629/AplicacionTecnologiasWeb/commit/16b15b14ca12057b0ccf2345dc437bb74660790a
