### ISSUE TITLE
Corregir alguna pagina en la que se usaba error.jsp

### ISSUE THREAD

**Issue by aangelcc** [melchor629/AplicacionTecnologiasWeb#23]
No me acuerdo cual pero se usaba en una en concreto. Ya que se ha borrado error.jsp hay que ver en cual es y arreglarlo

**Comment by melchor629** [comment]
![imagen](https://cloud.githubusercontent.com/assets/1056963/25717872/3b55d4e0-3104-11e7-8835-b5d900f74176.png)

Hay tres archivos que usa ese `error.jsp`.

**Comment by aangelcc** [comment]
Arreglao, se lanza RuntimeException
