### ISSUE TITLE
Función hash para passwords no funciona como se espera

### ISSUE THREAD

**Issue by aangelcc** [melchor629/AplicacionTecnologiasWeb#25]
El hash de mi con salt que está guardado en la BD es el siguiente:
`c7852be47c1c5e6d81456da6aed1336e1d65c1ad31429dc7b986276489c544f7`

Mientras que en el método `obtenerUsuario` de **UsuarioFacade** el hash generado para hacer la consulta es este:
`77cd816d0cf52ea09792c7df552c6415f8cfdbf114e2a72b520e827794b0531d`

Por lo tanto no hay forma de iniciar sesión.
Solución: Actualizar en la BD el hash generado
Ocurre con todos los usuarios

**Comment by melchor629** [comment]
<img width="628" alt="captura de pantalla 2017-05-29 a las 9 34 44" src="https://cloud.githubusercontent.com/assets/1056963/26540526/1b2b8c4e-4452-11e7-9041-42738d9845d1.png">

Yo revisaría tu instalación de Java o algo, porque todo funciona correctamente.
