### ISSUE TITLE
buscarBean.java da error cuando no se escriba nada ( se deja el placeholder)

### ISSUE THREAD

**Issue by RodriRR** [melchor629/AplicacionTecnologiasWeb#26]
Cuando nos dirigimos a .../busqueda.jsf y no introducimos en la caja de búsqueda ningún valor (quedando el placeholder "Buscar a..") y pinchamos en búsqueda se lanza un fallo en vez de devolver ningún resultado.

**Comment by melchor629** [comment]
Sin descripción no podemos saber como reproducir el error y arreglarlo

**Comment by RodriRR** [comment]
sorry men

**Comment by melchor629** [comment]
**Idea:** al poner nada podríamos mostrar ningún resultado el mensaje de error digo yo.

**Comment by xEDG** [comment]
He conseguido que si buscas "" (nada) salga el error del perro. No cierro, pendiente de revisión y discusión.

**Comment by melchor629** [comment]
Parece que funciona bien, lo he probado varias veces desde paginas distintas
