### ISSUE TITLE
Las páginas en las que se requiere iniciar sesión no redirigen fuera

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#31]
Hay que encontrar la manera de redirigir a fuera si no has iniciado sesión.

(Incompleto? no se xD)

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Añadir redirección cuando no has iniciado sesión](https://trello.com/c/2LzSHjPu/86-a%C3%B1adir-redirecci%C3%B3n-cuando-no-has-iniciado-sesi%C3%B3n)

**Comment by aangelcc** [comment]
https://stackoverflow.com/questions/23308207/how-to-redirect-a-jsf-page-to-home-page-if-session-does-not-exist
