### ISSUE TITLE
Mensaje JSF Error usando validadores

### ISSUE THREAD

**Issue by RodriRR** [melchor629/AplicacionTecnologiasWeb#38]
Al usar validadores funciona perfectamente, pero sale un cartel "MENSAJE DE JSF"

![image](https://user-images.githubusercontent.com/17813148/27280757-6573e3bc-54e9-11e7-99e6-7841eab7c13f.png)

**Comment by melchor629** [comment]
Eso ocurre por que está en modo debug, y los mensajes aparecen. Cuando se quite el modo debug, eso no aparecerá
