### ISSUE TITLE
Parece que en perfil no oculta las cosas que debería ocultar bien

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#39]
Desde Melchor al perfil de Francis aparecen dos cosas, aunque solo debería verse el botón.
<img width="358" alt="captura de pantalla 2017-06-19 a las 13 00 50" src="https://user-images.githubusercontent.com/1056963/27282251-78073d70-54ef-11e7-9cef-072031f4eb8e.png">

**Comment by xEDG** [comment]
![immelx](https://user-images.githubusercontent.com/17827406/27519997-80ef48ea-5a00-11e7-8c98-47af3c7ac68a.PNG)
![immelx2](https://user-images.githubusercontent.com/17827406/27519998-811b6f24-5a00-11e7-8e91-96c8937c2295.PNG)

Testeado con el ultimo push, ¿funciona?

**Comment by melchor629** [comment]
Sigue sin funcionar en mi caso, sale aun los dos a la vez. Puede ser que tenga que ver con el quitar amistad, volver a enviar y aceptar

**Comment by melchor629** [comment]
**Nueva info** En la BD sigue apareciendo la petición de amistad, a parte de tener a ambos de contactos. Puede que el aceptar petición de amistad esté mal.

**Comment by melchor629** [comment]
Ni rechazar ni aceptar borran de la BD la petición de amistad. Puede que no se esté borrando la petición correctamente de la relación bidireccional.

**Comment by melchor629** [comment]
0938580 Lo mismo con este commit se arregla. Por lo que he probado, ahora ya no hace eso raro de antes.
