### ISSUE TITLE
En perfil.jsp no se muestra ninguna información sobre los trabajos, aficiones y estudos

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#7]
El perfil sale incompleto, no aparece nada sobre los trabajos en los que ha estado dicha persona ni las aficiones.

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ANTES DE AÑADIR NUEVOS TRABAJOS, CORREGID LO QUE ESTÁ HECHO](https://trello.com/c/vK3CtVqh/38-antes-de-anadir-nuevos-trabajos-corregid-lo-que-esta-hecho)

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Visualizar Perfil](https://trello.com/c/wPshUSDl/7-visualizar-perfil)

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Visualizar Perfil de Amigo](https://trello.com/c/pcPm3zI4/15-visualizar-perfil-de-amigo)

**Comment by francis1196** [comment]
Se va a separar en 2. ahora aparecera en perfil

**Comment by aangelcc** [comment]
Estoy trabajando en ello

**Comment by aangelcc** [comment]
Sigo en ello. Modifico el issue para incluir trabajos, aficiones y estudios

**Comment by aangelcc** [comment]
Me falta mostrar los contactos, ya casi esta

**Comment by aangelcc** [comment]
Listo. Ya se muestra todo. 
Melchor: El perfil es todo tuyo.
Rediséñalo como consideres, aunque le he añadido una estructura basica para mostrar como lista todos los datos.
Por cada item que se muestra en [Estudios, Aficiones, Experiencia Laboral] debe haber un boton de editar y de eliminar. (Yo me encargo de poner los enlaces a los que llevan).
Simplemente necesito que hagas que ambos botones se muestren preferiblemente cuando tienes el raton situado por encima de un item.

**Comment by melchor629** [comment]
@aangelcc Pero, ¿No era un botón de editar para una sección entera? Eso me dijo Francis. Aclaraos anda

**Comment by melchor629** [comment]
Y si falta, entonces esto no está listo. Volviendo a abrir

**Comment by francis1196** [comment]
era un boton de editar y eliminar por aficion, trabajo y/o estudio. Hemos pensado que es la forma mas facil de hacerlo. al pulsar el boton de editar te lleva a un nuevo formulario y ahi editas el nombre de la aficion por ejemplo

**Comment by aangelcc** [comment]
Efectivamente uno por aficion

**Comment by melchor629** [comment]
@aangelcc Vale, eso va a ser algo mas complicado de diseñar, pero np. Manos a la obra a acabar esto. Cuando esté listo podré trabajar en el.

**Comment by aangelcc** [comment]
Ya lo hablamos Francis y yo y aclaramos eso, de ahi que te comente que hagas eso  @melchor629

**Comment by francis1196** [comment]
ya que antonio ha subido eso me pongo a terminar mi parte

**Comment by melchor629** [comment]
@aangelcc Pero no puedo trabajar si no habeis acabado de poner las cosas. Tu mismo has dicho que está incompleto @aangelcc

**Comment by aangelcc** [comment]
@melchor629 si ves que es muy coñazo diseñalo y que los botones se muestren en todos los items

**Comment by melchor629** [comment]
@aangelcc No complicado no creo que sea, pero antes me faltan los botones, como has dicho faltan. Por lo que los teneis que poner

**Comment by aangelcc** [comment]
@melchor629  es simplemente un boton de "Editar" y otro de "Eliminar" en cada item de los apartados aficion, trabajo y/o estudio

**Comment by melchor629** [comment]
@aangelcc Si lo sé, ¿tanto cuesta que lo pongais? Por que sin ellos no puedo hacer yo mi trabajo

**Comment by aangelcc** [comment]
ok lo pongo, arreglo antes un fallo que hay en una fachada

**Comment by melchor629** [comment]
@aangelcc Esperando estoy a que acabeis esto de una vez

**Comment by aangelcc** [comment]
@melchor629  ya he colocado los botones, estan puestos como un <a href="">
