### ISSUE TITLE
En modificar perfil, no se puede modificar los trabajos ni las aficiones

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#8]
Al modificar el perfil, no puedes añadir, eliminar ni modificar tanto trabajos como aficiones.

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ANTES DE AÑADIR NUEVOS TRABAJOS, CORREGID LO QUE ESTÁ HECHO](https://trello.com/c/vK3CtVqh/38-antes-de-anadir-nuevos-trabajos-corregid-lo-que-esta-hecho)

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modificar Perfil](https://trello.com/c/YdeAsdpo/10-modificar-perfil)

**Comment by francis1196** [comment]
Se va a separar en 2. ahora aparecera en perfil
