### ISSUE TITLE
No se recuperan los datos introducidos al haber un error

### ISSUE THREAD

**Issue by melchor629** [melchor629/AplicacionTecnologiasWeb#9]
En el registro, cuando se llega a un caso de error, no se recuperan los valores que ya ha introducido previamente obligando al usuario a volver a introducir todo de nuevo y encima arreglar el fallo que ha cometido.

Lo suyo seria que al fallar, se pasara al jsp los campos recibidos en el Servlet para que rellene los input automáticamente. Así es mas fácil para el usuario recuperarse del error.

**Comment by melchor629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Corregir formulario de registro](https://trello.com/c/N5oXETT5/36-corregir-formulario-de-registro)

**Comment by melchor629** [comment]
**(idea)** Yo creo que si en el jsp se pone algo como
```jsp
<% if(request.getParameter("..."); { %>
<input ... value="<%= request.getParameter("...") %>">
<% } else { %>
<input ...>
<% } %>
```

en cada `input` del registro.

**Comment by xEDG** [comment]
Done

**Comment by melchor629** [comment]
@xEDG Guay, cierra el _issue_ entonces :)
